/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HqRouteImport } from './routes/hq'
import { Route as KjRouteImport } from './routes/kj'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MeRouteImport } from './routes/me'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as VenuesSlugRouteImport } from './routes/venues.$slug'
import { Route as QKindKeyRouteImport } from './routes/q.$kind.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const KjRoute = KjRouteImport.update({
  id: '/kj',
  path: '/kj',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QKindKeyRoute = QKindKeyRouteImport.update({
  id: '/q/$kind/$key',
  path: '/q/$kind/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/hq': typeof HqRoute
  '/kj': typeof KjRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/songs': typeof SongsRoute
  '/welcome': typeof WelcomeRoute
  '/u/$handle': typeof UHandleRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/q/$kind/$key': typeof QKindKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/hq': typeof HqRoute
  '/kj': typeof KjRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/songs': typeof SongsRoute
  '/welcome': typeof WelcomeRoute
  '/u/$handle': typeof UHandleRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/q/$kind/$key': typeof QKindKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/hq': typeof HqRoute
  '/kj': typeof KjRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/songs': typeof SongsRoute
  '/welcome': typeof WelcomeRoute
  '/u/$handle': typeof UHandleRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/q/$kind/$key': typeof QKindKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feed'
    | '/friends'
    | '/hq'
    | '/kj'
    | '/live'
    | '/me'
    | '/scan'
    | '/songs'
    | '/welcome'
    | '/u/$handle'
    | '/venues/$slug'
    | '/q/$kind/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/feed'
    | '/friends'
    | '/hq'
    | '/kj'
    | '/live'
    | '/me'
    | '/scan'
    | '/songs'
    | '/welcome'
    | '/u/$handle'
    | '/venues/$slug'
    | '/q/$kind/$key'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/feed'
    | '/friends'
    | '/hq'
    | '/kj'
    | '/live'
    | '/me'
    | '/scan'
    | '/songs'
    | '/welcome'
    | '/u/$handle'
    | '/venues/$slug'
    | '/q/$kind/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeedRoute: typeof FeedRoute
  FriendsRoute: typeof FriendsRoute
  HqRoute: typeof HqRoute
  KjRoute: typeof KjRoute
  LiveRoute: typeof LiveRoute
  MeRoute: typeof MeRoute
  ScanRoute: typeof ScanRoute
  SongsRoute: typeof SongsRoute
  WelcomeRoute: typeof WelcomeRoute
  UHandleRoute: typeof UHandleRoute
  VenuesSlugRoute: typeof VenuesSlugRoute
  QKindKeyRoute: typeof QKindKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kj': {
      id: '/kj'
      path: '/kj'
      fullPath: '/kj'
      preLoaderRoute: typeof KjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$kind/$key': {
      id: '/q/$kind/$key'
      path: '/q/$kind/$key'
      fullPath: '/q/$kind/$key'
      preLoaderRoute: typeof QKindKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeedRoute: FeedRoute,
  FriendsRoute: FriendsRoute,
  HqRoute: HqRoute,
  KjRoute: KjRoute,
  LiveRoute: LiveRoute,
  MeRoute: MeRoute,
  ScanRoute: ScanRoute,
  SongsRoute: SongsRoute,
  WelcomeRoute: WelcomeRoute,
  UHandleRoute: UHandleRoute,
  VenuesSlugRoute: VenuesSlugRoute,
  QKindKeyRoute: QKindKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
