import { builtinModules } from 'node:module';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { build } from 'esbuild';

/**
 * Bundles the API (src/hosts/edge.ts) into one self-contained file for the Supabase Edge
 * Function `api`. Node built-ins get the `node:` prefix Deno needs; everything else is inlined.
 */
const outfile = resolve(import.meta.dirname, '../../../supabase/functions/api/index.js');
const builtins = new Set(builtinModules.flatMap((m) => [m, m.replace(/^node:/, '')]));

await build({
  entryPoints: [resolve(import.meta.dirname, '../src/hosts/edge.ts')],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  conditions: ['deno', 'worker'],
  minify: false,
  legalComments: 'none',
  banner: {
    js: [
      '// Generated by apps/api/scripts/build-edge.ts. Do not edit.',
      "import { createRequire as __createRequire } from 'node:module';",
      "import __process from 'node:process';",
      "import { Buffer as __Buffer } from 'node:buffer';",
      'const require = __createRequire(import.meta.url);',
      'globalThis.process ??= __process;',
      'globalThis.Buffer ??= __Buffer;',
    ].join('\n'),
  },
  plugins: [
    {
      name: 'node-builtins',
      setup(b) {
        b.onResolve({ filter: /^[a-z_:/]+$/ }, (args) => {
          const name = args.path.replace(/^node:/, '');
          return builtins.has(name) ? { path: `node:${name}`, external: true } : undefined;
        });
      },
    },
  ],
});

// Guard: demo/local-only code must never reach production.
const out = readFileSync(outfile, 'utf8');
const leaks = ['usr_jess', '/api/demo', 'PGlite', 'localRealtime', 'Demo controls'].filter((s) => out.includes(s));
if (leaks.length) {
  console.error(`✗ Edge bundle contains local/demo-only code: ${leaks.join(', ')}`);
  process.exit(1);
}
console.log(`✓ Edge function bundled → ${outfile} (${Math.round(out.length / 1024)} kB)`);
